import { en } from "vuetify/lib/locale";

export default {
  ...en,

  noDataText: "No data available",
  address: "Address",
  website: "Website",
  email: "Email",
  languages: "Languages",
  portuguese: "Portuguese",
  english: "English",
  spanish: "Spanish",
  contact: "Contact Info",
  socials: "Socials",
  levelNative: "Native",
  levelFluent: "Fluent",
  levelAdvanced: "Advanced",
  levelIntermediate: "Intermediate",
  levelBasic: "Basic",
  latestProjects: "Latest Projects",
  description: "Description",
  viewGithub: "View on Github",
  liveDemo: "Live Demo",
  technologies: "Technologies",
  experience: "Experience",
  education: "Education",
  skills: "Skills",
  tools: "Tools",
  database: "Database",
  presentTime: "Present",
  titleItTech: "IT Technician",
  titleCS: "Bachelor of Science - BS, Computer Science",
  descCv: "Curriculum Vitae is a dynamic Vue.js and Vuetify-powered web application that functions as a comprehensive resume. Showcasing my latest projects, professional experience, skills, education, and contact details, this page provides an interactive and aesthetically pleasing overview of my professional journey. Leveraging Vue.js for seamless interactivity and Vuetify for a polished material design, it ensures a responsive and visually appealing presentation of my skills and accomplishments. Explore my CV effortlessly and reach out easily through the provided contact information. 📄✨",
  descRecipe: "Recipes App is a front-end project developed for Vue.js learning purposes. It utilizes Vue.js, Vuetify, Axios, and VueRouter to create a responsive application. Users can explore and search for recipes based on cuisine, ingredients, and name, with detailed views showcasing preparation steps. Enjoy a seamless experience with this Vue.js-powered recipe app! 🍲 ",
  descEcommerce: "A comprehensive sales system developed as the final project for the Software Development Fundamentals course. The backend, powered by Spring Boot, leverages Java and Maven for robust API functionalities, including client and order management. The frontend, designed with Vue.js, offers an intuitive user interface for seamless interaction. Key features encompass client and order handling, product management, and insightful statistics generation. The combination of Spring Boot and Vue.js showcases proficiency in backend development and frontend design, reflecting a well-rounded skill set in Java, web development, and RESTful API implementation.",
  techSupport: "Technical Support Analyst Jr.",
  itIntern: "IT Intern",
  
};
