import { pt } from "vuetify/lib/locale";

export default {
  ...pt,

  noDataText: "Nenhum dado disponível",
  address: "Endereço",
  website: "Website",
  email: "Email",
  languages: "Idiomas",
  portuguese: "Português",
  english: "Inglês",
  spanish: "Espanhol",
  contact: "Contato",
  socials: "Redes Sociais",
  levelNative: "Nativo",
  levelFluent: "Fluente",
  levelAdvanced: "Avançado",
  levelIntermediate: "Intermediário",
  levelBasic: "Básico",
  latestProjects: "Últimos Projetos",
  description: "Descrição",
  viewGithub: "Ver no Github",
  liveDemo: "Demo",
  technologies: "Tecnologias",
  experience: "Experiência",
  education: "Formação",
  skills: "Skills",
  tools: "Ferramentas",
  database: "Banco de Dados",
  presentTime: "Atualmente",
  titleItTech: "Técnico em Informática",
  titleCS: "Bacharelado em Ciência da Computação",
  descCv: "O Curriculum Vitae é uma aplicação web dinâmica Vue.js e Vuetify que funciona como um currículo abrangente. Exibindo meus projetos mais recentes, experiência profissional, habilidades, educação e detalhes de contato, esta página oferece uma visão interativa e esteticamente agradável da minha jornada profissional. Utilizando o Vue.js para interatividade perfeita e o Vuetify para um design de material polido, garante uma apresentação responsiva e visualmente atraente das minhas habilidades e realizações. Explore meu CV facilmente e entre em contato facilmente por meio das informações fornecidas. 📄✨",
  descRecipe: "Recipes App é um projeto front-end desenvolvido para fins de aprendizado em Vue.js. Ele utiliza Vue.js, Vuetify, Axios e VueRouter para criar uma aplicação responsiva. Os usuários podem explorar e buscar receitas com base em culinária, ingredientes e nome, com visualizações detalhadas mostrando os passos de preparação. Aproveite uma experiência fluida com este aplicativo de receitas alimentado pelo Vue.js! 🍲",
  descEcommerce: "Um sistema abrangente de vendas desenvolvido como projeto final para o curso de Fundamentos do Desenvolvimento de Software. O backend, alimentado pelo Spring Boot, utiliza Java e Maven para funcionalidades robustas de API, incluindo gerenciamento de clientes e pedidos. O frontend, projetado com Vue.js, oferece uma interface de usuário intuitiva para interação perfeita. Recursos-chave incluem o gerenciamento de clientes e pedidos, gestão de produtos e geração de estatísticas perspicazes. A combinação de Spring Boot e Vue.js demonstra proficiência no desenvolvimento de backend e design de frontend, refletindo um conjunto de habilidades abrangente em Java, desenvolvimento web e implementação de API RESTful.",
};
